"""CONSTANTS FOR THE MUSIC TRANSFER PROGRAM"""
import os

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")
SPOTIFY_API_SCOPES = os.getenv("SPOTIFY_API_SCOPES")
